Wa 32
Hommasoft/wappuapp-adminpanel pull request #4
Opened 2017-11-25 16:32 UTC by Aivoapina

Basic feed implementation.

2017-11-25 17:16 UTC, Jeva92 requested changes
"This branch has conflicts that must be resolved" 
Tämä pitää korjata ihan ensimmäisenä. 

All in all, koodi näyttää hyvältä, mutta pikkujuttuja iski silmään.

2017-11-25 17:16 UTC, Jeva92 commented on wappuapp-adminpanel/src/components/feed/feedlist.js
> +import FeedItem from './feeditem.js';
importeissa kannattaa .js pääte jättää pois. Oli useammassa paikassa näitä

2017-11-25 17:16 UTC, Jeva92 commented on wappuapp-adminpanel/src/constants/loadingstates.js
> +  NONE: 'none',
Onko tämä NONE todellakin tarpeellinen? (Rehellinen kysymys siis, ei kritiikkiä)

2017-11-25 17:16 UTC, Jeva92 commented on wappuapp-adminpanel/src/routes/index.js
> +      <Route exact path="/feed" component={FeedList} />
Kyseessä on kuitenkin admintyökalu. Olisiko tarkoituksenmukaista, että /feed näkyy admin työkalussa vain jos on kirjautunut?

2017-11-26 11:32 UTC, Jeva92 commented
Muutosten jälkeen näyttää hyvältä

2017-11-26 11:33 UTC, Jeva92 approved these changes

2017-11-26 12:35 UTC, mikael-lagerbom approved these changes

2017-11-26 14:05 UTC, merged